spring:
  datasource:
    url: jdbc:mysql://localhost:3306/inventory-sys
    username: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8081/realms/order-fulfillment-realm
          jwk-set-uri: http://localhost:8081/realms/order-fulfillment-realm/protocol/openid-connect/certs
